Adds support for configurable user-agent that ignores logging
echoboomer/incident-bot pull request #259
Opened 2023-06-16 16:17 UTC by ImDevinC

This change updates the ignored user-agent for logging to be a configurable value rather than harcoded

2023-06-27 13:40 UTC, echoboomer requested changes

2023-06-27 13:40 UTC, echoboomer commented on version
> +v1.4.11
Version should also be changed on line 11 in `backend/config.py`.

2023-06-27 22:04 UTC, merged

2023-07-10 18:03 UTC, ImDevinC commented
I'm currently traveling but will check tomorrow.

2023-07-11 14:25 UTC, ImDevinC commented
I'm able to reproduce, and I know why. I will try to have a fix soon

2023-07-11 16:17 UTC, ImDevinC commented
Addressed in https://github.com/echoboomer/incident-bot/pull/280