Add Slack channel name to actions description
echoboomer/incident-bot pull request #500
Opened 2024-04-16 02:04 UTC by i5o

## Describe your changes

- Added Slack channel name to the actions description of the issue, sometimes in mobile the Join button doesn't work. Having it directly linked it's an additional approach that fixes this.

## Issue number and link

## Checklist before requesting a review

- [ ] I have properly bumped all version refs by running `./scripts/version-bump.sh v<new>` from project root - for example `./scripts/version-bump.sh v1.9.3`

2024-05-16 01:11 UTC, echoboomer commented
@i5o would you remind rebasing this and updating the version?

2024-05-16 03:33 UTC, i5o commented
@echoboomer done ;)

2024-05-23 23:49 UTC, echoboomer requested changes
Left a comment.

2024-05-23 23:49 UTC, echoboomer commented on backend/bot/templates/incident/digest_notification.py
> +                    + f"\n#{incident_channel_details.get("name")}",
You'll need to use single quotes here around `name`.

2024-05-24 00:25 UTC, i5o commented on backend/bot/templates/incident/digest_notification.py
> +                    + f"\n#{incident_channel_details.get("name")}",
```suggestion
                    + f"\n#{incident_channel_details.get('name')}",
```

2024-06-14 00:49 UTC, echoboomer commented
Looks like the tests just need some tweaks.

2024-06-14 16:30 UTC, i5o commented
@echoboomer can you take a look now?

2024-06-17 21:36 UTC, echoboomer approved these changes

2024-06-17 21:36 UTC, merged